name: Build and push Docker image
on:
  push:
    branches:
      - OTAT-340-new

env:
  GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Packages registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: docker.pkg.github.com/${{ github.repository }}/flickit-platform-frontend:${{ steps.vars.outputs.tag }}
