name: Build and Push Docker Image

on:
  push:
    branches:
      - stage

env:
  GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=stage" >> $GITHUB_ENV
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: avansoft
          password: ${{ secrets.GH_PACKAGES_TOKEN }}
      - name: Build and push frontend image to GitHub Container Registry
        run: |
          docker build -t ghcr.io/avansoft/flickit-platform-frontend:${{ steps.vars.outputs.tag }} ./frontend
          docker push ghcr.io/avansoft/flickit-platform-frontend:${{ steps.vars.outputs.tag }}
