name: Merge main into stage

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Merge main into stage
      run: |
        git checkout stage
        git merge main --no-ff --no-edit
        git push origin stage
